### ISSUE TITLE
鼠须管 如何调整词频或删除

### ISSUE THREAD

**Issue by fgheng** [Iorest/rime-setting#1]
您好，我使用您D配置出现了问题，但是我不太了解rime是怎么配置D，情况与[该问题](https://github.com/rime/squirrel/issues/481)描述一致。
请问您知道是ZenM回事么？非常感谢。

**Comment by Iorest** [comment]
能给一些详细信息吗？我没法复现您的问题.

**Comment by fgheng** [comment]
您好，我找到解决方案了
https://github.com/BlindingDark/rime-easy-en#%E6%B7%B7%E8%BE%93%E6%97%B6%E8%8B%B1%E6%96%87%E5%8D%95%E8%AF%8D%E6%8E%92%E7%9A%84%E5%A4%AA%E9%9D%A0%E5%90%8E
